version: '3.8'

services:
  tests:
    build: .
    container_name: effective_mobile_tests
    working_dir: /app
    volumes:
      - .:/app
    command: behave features/main_page.feature --no-capture