[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --verbose --strict-markers --disable-warnings --alluredir=/app/reports/allure-results
markers =
    ui: UI Tests
    navigation: Navigation Tests
    smoke: Smoke Tests